opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - implicit_return
  - joined_default_parameter
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - single_test_class
  - unneeded_parentheses_in_closure_argument
  - private_over_fileprivate

disabled_rules:
  - file_length
  - line_length
  - function_body_length
  - type_body_length

included:
  - Routes